In [1]:
import numpy as np
import pandas as pd

In [10]:
dict = {
    "Name" : ["Sabuj","Ram","Subham"],
    "Marks" : [99,68,87],
    "City" : ['kolkata','Naipur','Egra',]
}

df = pd.DataFrame(dict)
df.to_csv('Friend.csv') # the csv file contains indices
df.to_csv('Friend_False_index.csv',index=False) # indices will not be there
df

     Name  Marks     City
0   Sabuj     99  kolkata
1     Ram     68   Naipur
2  Subham     87     Egra

In [ ]:
import pandas as pd
dict = {
    "Name" : ["Sabuj","Ram","Subham"],
    "Marks" : [99,68,87],
    "City" : ['kolkata','Naipur','Egra',]
}

df.head(2) # will show the first two rows
df.tail(2) # will show the last two rows

     Name  Marks    City
1     Ram     68  Naipur
2  Subham     87    Egra